import Door from "@/components/Door/page";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import { CartWishlistProvider } from "@/context/CartWishlistContext";
import ThemeProvider from "@/lib/ThemeProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "400 600",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "400 600",
});

export const metadata: Metadata = {
  title: "GrassRootz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <StoreProvider>
          <div className="relative">
            <Door />
            <CartWishlistProvider>
              <Navbar />

              <AntdRegistry>
                <ThemeProvider>{children}</ThemeProvider>
              </AntdRegistry>

              <Footer />
            </CartWishlistProvider>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
